# Generated by Django 2.0 on 2018-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinRedirectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customUrl', models.CharField(max_length=10, unique=True)),
                ('url1', models.URLField()),
                ('url2', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RandomRedirectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customUrl', models.CharField(max_length=10, unique=True)),
                ('url1', models.URLField(blank=True, null=True)),
                ('url2', models.URLField(blank=True, null=True)),
                ('url3', models.URLField(blank=True, null=True)),
                ('url4', models.URLField(blank=True, null=True)),
                ('url5', models.URLField(blank=True, null=True)),
                ('url6', models.URLField(blank=True, null=True)),
                ('url7', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
