# Generated by Django 2.0 on 2018-04-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customUrl', models.CharField(max_length=10, unique=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
